import 'dart:io';

import 'runtime_placeholder_registry.dart';

final class RuntimePlaceholderFinding {
  const RuntimePlaceholderFinding({
    required this.kind,
    required this.sourcePath,
    required this.line,
  });

  final RuntimePlaceholderKind kind;
  final String sourcePath;

  /// Line number is informational only.
  ///
  /// It is intentionally NOT part of the fingerprint because moving code
  /// inside a file must not create a fake "new architecture violation".
  final int line;

  String get fingerprint => '${kind.name}|$sourcePath';

  @override
  String toString() => '$fingerprint|line=$line';
}

final class RuntimePlaceholderScanner {
  RuntimePlaceholderScanner({Directory? projectRoot})
    : projectRoot = projectRoot ?? _discoverProjectRoot();

  final Directory projectRoot;

  List<RuntimePlaceholderFinding> scan() {
    final libDirectory = Directory(
      '${projectRoot.path}${Platform.pathSeparator}lib',
    );

    if (!libDirectory.existsSync()) {
      throw StateError(
        'Unable to scan runtime placeholders: '
        'lib/ was not found at ${libDirectory.path}.',
      );
    }

    final findings = <RuntimePlaceholderFinding>[];

    final files =
        libDirectory
            .listSync(recursive: true, followLinks: false)
            .whereType<File>()
            .where((file) => file.path.endsWith('.dart'))
            .toList()
          ..sort((a, b) => a.path.compareTo(b.path));

    for (final file in files) {
      final sourcePath = _relativeLibPath(file);

      if (_isExcludedRuntimePath(sourcePath)) {
        continue;
      }

      final content = file.readAsStringSync();

      for (final rule in runtimePlaceholderRegistry) {
        final regex = RegExp(rule.pattern, multiLine: true);

        for (final match in regex.allMatches(content)) {
          findings.add(
            RuntimePlaceholderFinding(
              kind: rule.kind,
              sourcePath: sourcePath,
              line: _lineNumber(content, match.start),
            ),
          );
        }
      }
    }

    findings.sort((a, b) {
      final fingerprintCompare = a.fingerprint.compareTo(b.fingerprint);

      if (fingerprintCompare != 0) {
        return fingerprintCompare;
      }

      return a.line.compareTo(b.line);
    });

    return List.unmodifiable(findings);
  }

  Set<String> uniqueFingerprints() {
    return scan().map((finding) => finding.fingerprint).toSet();
  }

  bool _isExcludedRuntimePath(String sourcePath) {
    final normalized = sourcePath.toLowerCase();

    // Generated FlutterFire configuration.
    //
    // UnsupportedError in this file represents unsupported/configuration
    // platform guards generated by FlutterFire, not unfinished Mentora
    // runtime behavior.
    if (normalized == 'firebase_options.dart') {
      return true;
    }

    const excludedSegments = <String>[
      '/test/',
      '/tests/',
      '/fixture/',
      '/fixtures/',
      '/testing/',
    ];

    for (final segment in excludedSegments) {
      if ('/$normalized'.contains(segment)) {
        return true;
      }
    }

    return false;
  }

  int _lineNumber(String content, int offset) {
    if (offset <= 0) {
      return 1;
    }

    var line = 1;

    for (var index = 0; index < offset; index++) {
      if (content.codeUnitAt(index) == 10) {
        line += 1;
      }
    }

    return line;
  }

  String _relativeLibPath(File file) {
    final libRoot = Directory(
      '${projectRoot.path}${Platform.pathSeparator}lib',
    ).absolute.path;

    final absoluteFilePath = file.absolute.path;

    var relativePath = absoluteFilePath.substring(libRoot.length);

    while (relativePath.startsWith('/') || relativePath.startsWith('\\')) {
      relativePath = relativePath.substring(1);
    }

    return relativePath.replaceAll('\\', '/');
  }

  static Directory _discoverProjectRoot() {
    var current = Directory.current.absolute;

    while (true) {
      final pubspec = File('${current.path}/pubspec.yaml');

      final lib = Directory('${current.path}/lib');

      if (pubspec.existsSync() && lib.existsSync()) {
        return current;
      }

      final parent = current.parent;

      if (parent.path == current.path) {
        throw StateError(
          'Unable to locate Mentora project root '
          'from ${Directory.current.path}.',
        );
      }

      current = parent;
    }
  }
}
