// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw6Fo4Semych68mW_CYUeQ-uCvpT4tk3I',
    appId: '1:742968306379:web:5cf822167c3563a5c7c94e',
    messagingSenderId: '742968306379',
    projectId: 'mentora-7e926',
    authDomain: 'mentora-7e926.firebaseapp.com',
    storageBucket: 'mentora-7e926.firebasestorage.app',
    measurementId: 'G-KNV0ZVCDY4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3nvmcLP5Y6_nNXVlyZux6uONK7ZXIbrA',
    appId: '1:742968306379:android:2be147a61663f34fc7c94e',
    messagingSenderId: '742968306379',
    projectId: 'mentora-7e926',
    storageBucket: 'mentora-7e926.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDPSONRUMlPBMfxcNv7m4eXPgvb9J-4eo',
    appId: '1:742968306379:ios:cff81bdab13a643ec7c94e',
    messagingSenderId: '742968306379',
    projectId: 'mentora-7e926',
    storageBucket: 'mentora-7e926.firebasestorage.app',
    iosBundleId: 'com.mentora.africa.mentora',
  );
}
